name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install  # Change this based on your tech stack

      - name: Run Tests
        run: npm test  # Add your test command here

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Server
        run: |
          echo "Deploying application..."
          # Add deployment commands (e.g., SSH into a server, push to Firebase, etc.)
